### ISSUE TITLE
could not load the waf tool swig from ................

### ISSUE THREAD

**Issue by gongqiang** [MTG/gaia#29]
when i execute ./waf configure --with-python-bindings,  it shows couldn't load the waf tool swig

when i execute ./waf configure --download --with-python-bindings.  it shows could not load the Waf tool

Don't know how to fix this one,  is it a problem about the version?  wish some boss could help me

**Comment by gongqiang** [comment]
download problem.   just download the swig.py  and manually add it to the /warlib/extras/ dir.  then problem solved

**Comment by lifavor** [comment]
i have the sample problem, but i can not find where to donwload ------> swig.py , wish you boss could help me

**Comment by gongqiang** [comment]
[swig.txt](https://github.com/MTG/gaia/files/225155/swig.txt)

change it to swig.py     good luck

**Comment by lifavor** [comment]
Appreciate for your help.I encounted some errors about writing metadata 'gaia2.pc' after putting the swig.py into /warlib/extras/ dir.  I suddenlly realized the reason that "./waf configure --download ...."  took at least 3 minute and 'could not load the waf tool swig'  dues to GFW.   I get  'Downloaded swig from http://waf.googlecode.com/git//waflib/extras/swig.py'  on the ohter side of GFW,and then successfully make installed.

**Comment by joshdevins** [comment]
The problem with `--download` is that Google Code no longer exists. The code for waf tools is not accessible anymore. This project should upgrade to the latest version of waf.

**Comment by danieleghisi** [comment]
Hi guys,
I had the same error (btw http://waf.googlecode.com/git//waflib/extras/swig.py doesn't seem to exist any longer). I've added swig.py to the waflib/extras folder, but I still get some python errors while running ./waf --help. Might be a versioning problem? Does anyone know how to fix this?
Here's the output from ./waf --help.

Thanks,
Daniele


MBPdiDaniele2:gaia-2.4.4 danieleghisi$ ./waf --help
Waf: The wscript in '/Users/danieleghisi/LibrariesAndStuff/gaia-2.4.4' is unreadable
Traceback (most recent call last):
  File "/Users/danieleghisi/LibrariesAndStuff/gaia-2.4.4/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 87, in waf_entry_point
    set_main_module(Context.run_dir+os.sep+Context.WSCRIPT_FILE)
  File "/Users/danieleghisi/LibrariesAndStuff/gaia-2.4.4/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Scripting.py", line 112, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/Users/danieleghisi/LibrariesAndStuff/gaia-2.4.4/.waf3-1.7.9-16e1644c17ba46b94844133bac6e2a8c/waflib/Context.py", line 281, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/Users/danieleghisi/LibrariesAndStuff/gaia-2.4.4/wscript", line 197
    print conf.env
             ^
SyntaxError: Missing parentheses in call to 'print'
MBPdiDaniele2:gaia-2.4.4 danieleghisi$

**Comment by alastair** [comment]
We're aware of this problem, and will work to fix it as soon as we can. 

Your specific problem looks like you're using python3. Essentia and gaia are only supported with python2 at the moment.

**Comment by danieleghisi** [comment]
Thanks, i'll stay tuned then.
Thanks again for your work!

**Comment by gongqiang** [comment]
from the error, seems that just add parentheses to conf.env may solve the problem: print(conf.env)

**Comment by danieleghisi** [comment]
Hi, I solved that by replacing all occurrences of 
#!/usr/bin/env python
with
#!/usr/bin/env python2.7
which seems to be the safe way to go (to avoid messing up with pythong versions) - but I'm absolutely no expert.

@gongqiang This wasn't however the main issue: even with python2.7 the "could not load the waf tool swig from" issue still stands.

**Comment by kartikgupta0909** [comment]
Hi,
    I was trying to package the library for the MTG PPA for ubuntu, and got the same build error when it was being build on the ubuntu servers. On my local machine I was able to handle the error by including swig.py manually in the path, but this should be packaged with the library itself as mentioned above in the comments. Could you make this a priority bug as I need it for packaging the library for ubuntu 16.04. After this anybody who wishes to use the library would simply able to install the library by running the apt-get install command.

**Comment by dbogdanov** [comment]
Waf is updated now in the master branch.

**Comment by danieleghisi** [comment]
Sorry to open this again... I've downloaded the master branch, changed all headers to python2.7, but I still get
"waf: error: no such option: --download"

when I try to run "./waf configure --download" as written in the readme.
Same error via homebrew.

Am I doing something wrong?
Thanks again,
Daniele

**Comment by alastair** [comment]
You no longer need the `--download` option. We will fix the readme.

**Comment by dbogdanov** [comment]
Fixed in 98528c3e17783bbbe050552d0571aeade3cd6c49

**Comment by danieleghisi** [comment]
Thanks!
I was indeed able to install it properly without the --python-binding options.

As soon as I include this option, build fails (log below)
Not sure if it's because I should clean everything up properly before re-building it. (If so is there a non-manual way to do that?)
Here's the failing part:

[85/93] Processing src/bindings/gaia.swig
Assertion failed: (!Getattr(n, "defaultargs")), function update_defaultargs, file parser.y, line 667.

Waf: Leaving directory `/Users/danieleghisi/LibrariesAndStuff/gaia-master/build'
Build failed
 -> task in '_gaia2' failed (exit status -6): 
	{task 4409922704: swig gaia.swig -> gaia2.swigwrap_1.cxx,gaia2.py}
['/usr/local/bin/swig', '-c++', '-python', '-w451', '-o', '/Users/danieleghisi/LibrariesAndStuff/gaia-master/build/src/bindings/gaia2.swigwrap_1.cxx', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/build/src', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/src', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/build/src/bindings', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/src/bindings', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/build/src/metrics', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/src/metrics', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/build/src/3rdparty', '-I/Users/danieleghisi/LibrariesAndStuff/gaia-master/src/3rdparty', '-I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7', '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers', '-I/usr/local/Cellar/qt/4.8.7_2/include', '-I/usr/local/Cellar/qt/4.8.7_2/include/QtCore', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="Undefined"', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_PYEXT=1', '-DNDEBUG', '-DHAVE_QTCORE=1', '-DQT_SHARED', '-DHAVE_YAML=1', '../src/bindings/gaia.swig']

**Comment by alastair** [comment]
This error is https://github.com/MTG/gaia/issues/35, you need to either downgrade swig to 3.0.7 or upgrade to 3.0.9

**Comment by danieleghisi** [comment]
Ok, I've upgraded to 3.0.9, not --with-python-bindings works.
However (sorry guys, I'll get there...) loading the gaia2 python package fails.
Here's the (apparently swig-related) issue when I try to compile the doc (the gaia2 folder is in the usr/local/lib/python2.7/site-packages/ folder, so that looks correct)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gaia2/__init__.py", line 18, in <module>
    _gaia2 = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/gaia2/__init__.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _gaia2

**Comment by thisfred** [comment]
After manually building swig 3.0.10 and rerunning the configure, ./waf succeed, but I too now get the the above import error: 

`ImportError: No module named _gaia2`

**Comment by kartikgupta0909** [comment]
Are you using the virtual machine?

**Comment by thisfred** [comment]
@kartikgupta0909: I'm not sure what you mean by that, but I'm not running Ubuntu under a VM if that's the question.

**Comment by kartikgupta0909** [comment]
yeah that was the question. are you getting the error when you do import gaia2?

**Comment by thisfred** [comment]
I get it both when I do `import gaia2`, or `from gaia2 import DataSet`.

**Comment by kartikgupta0909** [comment]
I was getting this error too. Could you give me the complete traceback.

**Comment by thisfred** [comment]
```
>>> from gaia2 import DataSet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 21, in <module>
    _gaia2 = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 20, in swig_import_helper
    return importlib.import_module('_gaia2')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _gaia2
```

**Comment by kartikgupta0909** [comment]
Oh, mine was different so I could resolve it. Never encountered this error before.

**Comment by alastair** [comment]
@thisfred We're aware of this issue, and are tracking it in https://github.com/MTG/gaia/issues/35

You should be able to fix it temporarily by moving `/usr/local/lib/python2.7/site-packages/gaia2/_gaia2.so` up one level to the `site-packages` directory.

**Comment by thisfred** [comment]
the workaround did it for me, thanks!
